name: shell

# Last updated: 2023-03-17 16:27:02.843545108 +0000 GMT m=+0.000681794

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: actuated
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master
      - name: Connect to the actuated SSH gateway
        uses: alexellis/actuated-ssh-gateway-action@master
        with:
          gatewayaddr: actuated-gw.o6s.io
          secure: true
      - name: Setup a blocking tmux session
        uses: alexellis/block-with-tmux-action@master
